---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-deprecated-api
  annotations:
    policies.kyverno.io/title: Check for deprecated HelmRelease API version
    policies.kyverno.io/category: Flux
    policies.kyverno.io/minversion: 1.13.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Flux APIs
spec:
  background: true
  rules:
  - name: validate-flux-v2.4-removals
    match:
      any:
      - resources:
          kinds:
          - helm.toolkit.fluxcd.io/*/HelmRelease
    celPreconditions:
      - name: "allowed-api-versions"
        expression: "object.apiVersion in ['helm.toolkit.fluxcd.io/v2beta1', 'helm.toolkit.fluxcd.io/v2beta2']"
    validate:
      failureAction: Audit
      cel:
        expressions:
          - expression: "false"
            messageExpression: >-
              object.apiVersion + '/' + object.kind + ' is deprecated and will be removed in Flux v2.4.
              See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/'
   