---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-deprecated-api
  annotations:
    policies.kyverno.io/title: Check for deprecated HelmRelease API version
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Flux APIs
spec:
  validationFailureAction: Audit
  background: true  
  rules:
    - name: flux-helm-controller-deprecated-api
      match:
        any:
        - resources:
            kinds:
            - helm.toolkit.fluxcd.io/*/HelmRelease 
      celPreconditions:
        - name: "allowed-api-versions"
          expression: "!(object.apiVersion in ['helm.toolkit.fluxcd.io/v2'])"
      validate:
        cel:
          expressions:
            - expression: "false"
              messageExpression: >-
                object.apiVersion + '/' + object.kind + request.object.metadata.name + request.object.metadata.namespace + ' is deprecated in Flux v2.4.
                See: https://'
    - name: flux-source-controller-deprecated-api
      match:
        any:
        - resources:
            kinds:
            - source.toolkit.fluxcd.io/*/Bucket
            - source.toolkit.fluxcd.io/*/GitRepository
            - source.toolkit.fluxcd.io/*/HelmChart
            - source.toolkit.fluxcd.io/*/HelmRepository
      celPreconditions:
        - name: "allowed-api-versions"
          expression: "!(object.apiVersion in ['helm.toolkit.fluxcd.io/v1'])"
      validate:
        cel:
          expressions:
            - expression: "false"
              messageExpression: >-
                object.apiVersion + '/' + object.kind + request.object.metadata.name + request.object.metadata.namespace + ' is deprecated in Flux v2.4.
                See: https://'
   