---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-deprecated-api
  annotations:
    policies.kyverno.io/title: Check for deprecated HelmRelease API version
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Flux APIs
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: flux-helm-controller-deprecated-api
      match:
        any:
          - resources:
            kinds:
              - helm.toolkit.fluxcd.io/*/HelmRelease    
      celPreconditions:
        - name: "allowed-api-versions"
          expression: "object.apiVersion in ['helm.toolkit.fluxcd.io/v2']"
      validate:
        cel:
          expressions:
            - expression: "true"
              messageExpression: >-
                object.apiVersion + '/' + object.kind + ' is deprecated in Flux v2.4.
                See: https://'
    # - name: source-controller-api-v1
    #   context:
    #     - name: validSourceControllerApiVersionStable
    #       variable:
    #         value: source.toolkit.fluxcd.io/v12
    #   match:
    #     any:
    #       - resources:
    #           kinds:
    #             - Bucket
    #             - GitRepository
    #             - HelmChart
    #             - HelmRepository
    #   validate:
    #     failureAction: Audit
    #     message: >-
    #       Kind "{{ request.object.kind }}" with
    #       name "{{ request.object.metadata.name }}" in namespace "{{ request.object.metadata.namespace }}"
    #       is using deprecated API version "{{ request.object.apiVersion }}".
    #       Use API version "{{ validSourceControllerApiVersionStable }}".
    #       See: https://v2-4.docs.fluxcd.io/flux/components/source/api/v1/
    #     deny:
    #       conditions:
    #         any:
    #           - key: "{{ request.object.apiVersion }}"
    #             operator: AnyNotIn
    #             value: "{{ validSourceControllerApiVersionStable }}"
                
    # - name: flux-source-controller-deprecated-api
    #   context:
    #     - name: validSourceControllerApiVersion
    #       variable:
    #         value: source.toolkit.fluxcd.io/v1
    #   match:
    #     any:
    #       - resources:
    #           kinds:
    #             - Bucket
    #             - GitRepository
    #             - HelmChart
    #             - HelmRepository
    #   validate:
    #     message: >-
    #       "{{ request.object.kind }}" with
    #       name "{{ request.object.metadata.name }}" in namespace "{{ request.object.metadata.namespace }}"
    #       is using deprecated API version "{{ request.object.apiVersion }}".
    #       Use API version "{{ validSourceControllerApiVersion }}".
    #       See: https://fluxcd.io/flux/components/source/api/v1/
    #     pattern:
    #       apiVersion: "{{ validSourceControllerApiVersion }}"
    # - name: flux-kustomize-controller-deprecated-api
    #   context:
    #     - name: validKustomizeControllerApiVersion
    #       variable:
    #         value: kustomize.toolkit.fluxcd.io/v1
    #   match:
    #     any:
    #       - resources:
    #           kinds:
    #             - kustomize.toolkit.fluxcd.io/*/Kustomization # only match Flux Kustomization resources
    #   validate:
    #     message: >-
    #       "{{ request.object.kind }}" with
    #       name "{{ request.object.metadata.name }}" in namespace "{{ request.object.metadata.namespace }}"
    #       is using deprecated API version "{{ request.object.apiVersion }}".
    #       Use API version "{{ validKustomizeControllerApiVersion }}".
    #       See: https://fluxcd.io/flux/components/kustomize/api/v1/
    #     pattern:
    #       apiVersion: "{{ validKustomizeControllerApiVersion }}"


