---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-deprecated-api
  annotations:
    policies.kyverno.io/title: Check for deprecated HelmRelease API version
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Flux APIs
spec:
  background: true
  
  rules:
    - name: flux-helm-controller-deprecated-api
      match:
        any:
        - resources:
            kinds:
            - HelmRelease 
            namespaces:
            - ingress-nginx
      preconditions:
        all:
        - key: "{{request.object.apiVersion}}"
          operator: AllNotIn
          value:
          - helm.toolkit.fluxcd.io/v2
      validate:
        failureAction: Audit
        cel:
          expressions:
            - expression: "false"
              messageExpression: >-
                'Kind ' + request.object.kind + ' with ' +
                'name ' + request.object.metadata.name + ' in namespace ' + request.object.metadata.namespace +
                'is using deprecated API version ' + request.object.apiVersion +
                'Use API version "helm.toolkit.fluxcd.io/v2".'
      # celPreconditions:
      #    - name: "allowed-api-versions"
      #      expression: "!(object.apiVersion in ['helm.toolkit.fluxcd.io/v2'])"
      # validate:
      #   failureAction: Audit
      #   cel:
      #     expressions:
      #       - expression: "false"
      #       # - expression: "object.apiVersion in ['helm.toolkit.fluxcd.io/v2']"
      #         messageExpression: >-
      #           object.apiVersion + '/' + object.kind + ' in ns ' + namespaceObject.metadata.name + ' is deprecated in Flux v2.4.
      #           See: https://'
    # - name: flux-source-controller-deprecated-api
    #   match:
    #     any:
    #     - resources:
    #         kinds:
    #         - source.toolkit.fluxcd.io/*/Bucket
    #         - source.toolkit.fluxcd.io/*/GitRepository
    #         - source.toolkit.fluxcd.io/*/HelmChart
    #         - source.toolkit.fluxcd.io/*/HelmRepository
    #   celPreconditions:
    #     - name: "allowed-api-versions"
    #       expression: "!(object.apiVersion in ['source.toolkit.fluxcd.io/v1'])"
    #   validate:
    #     failureAction: Audit
    #     cel:
    #       expressions:
    #         - expression: "false"
    #           messageExpression: >-
    #             object.apiVersion + '/' + object.kind + ' is deprecated in Flux v2.4.
    #             See: https://'
   