apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: secret-sauce
  namespace: webapp
spec:
  externalSecretName: "secret-sauce-ces"
  refreshInterval: 1m
  namespaceSelectors:
  - matchLabels:
      cool: label
  
  externalSecretSpec:
    secretStoreRef:
      name: doppler-auth-api
      kind: SecretStore
    refreshInterval: "10m"
    target:
      name: secret-sauce-ces
      creationPolicy: 'Owner'
    dataFrom:
      - find:
          name:
            regexp: .*   