apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:  
  name: doppler-auth-api-css
spec:  
  provider:    
    doppler:      
      auth:        
        secretRef:          
          dopplerToken:            
            name: doppler-token-auth-api            
            key: dopplerToken