apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: secret-sauce-ces
  namespace: webapp
spec:
  externalSecretName: secret-sauce-ces
  refreshTime: 1m
  namespaceSelectors:
  - matchLabels:
      cool: label
  
  externalSecretSpec:
    secretStoreRef:
      name: doppler-auth-api-css
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: secret-sauce-ces
      creationPolicy: Owner
    dataFrom:
      - find:
          name:
            regexp: .*   