apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-test-webapp
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: secret-sauce
  config: prd
  managedSecret:
    name: secret-sauce-webapp
    namespace: webapp
    type: Opaque
  secrets:
    - SECRET_SAUCE
