apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:  
  name: secret-sauce
  namespace: external-secrets
spec:  
  refreshInterval: 1m
  secretStoreRef:    
    kind: SecretStore    
    name: doppler-auth-api  
  target:    
    name: secret-sauce  
  data:    
    - secretKey: SECRET_SAUCE      
      remoteRef:        
        key: SECRET_SAUCE