apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:  
  name: secret-sauce
  namespace: webapp
spec:  
  refreshInterval: 1m
  secretStoreRef:    
    kind: SecretStore    
    name: doppler-auth-api  
  target:    
    name: secret-sauce  
    deletionPolicy: Delete
  dataFrom:
    # - find:
    #     name:
    #       regexp: .*
    - secretKey: SECRET_SAUCE      
      remoteRef:        
        key: SECRET_SAUCE