apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: webapp
  namespace: webapp
resources:
  - deployment.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - service.yaml