apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  # driftDetection:
  #   mode: enabled
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    image:
      tag: 6.8.0
    ingress:
      hosts:
        - host: podinfo.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
