---
apiVersion: v1
kind: Namespace
metadata:
  name: doppler-operator-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: doppler-kubernetes-operator
  namespace: doppler-operator-system
spec:
  interval: 24h
  url: https://helm.doppler.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: doppler-kubernetes-operator
  namespace: doppler-operator-system
spec:
  interval: 5m
  chart:
    spec:
      chart: doppler-kubernetes-operator
      version: 1.5.7
      sourceRef:
        kind: HelmRepository
        name: doppler-kubernetes-operator
        namespace: doppler-operator-system
      interval: 5m
  values:
    installCRDs: true