---
apiVersion: v1
kind: Namespace
metadata:
  name: stakater-reloader
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: stakater-reloader
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: v1.3.0
      sourceRef:
        kind: HelmRepository
        name: helm-stakater
        namespace: stakater-reloader
  values:
    reloader:
      deployment:
        securityContext:
        image:
          name: stakater/reloader
          tag: v1.3.0

