apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-test
  namespace: webapp-2
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: secret-sauce
  config: prd
  managedSecret:
    name: dopplersecret-test
    namespace: webapp-2
    type: Opaque